### ISSUE TITLE
Error on first split

### ISSUE THREAD

**Issue by solanatreehouseclub** [stephenwilliams1990/split-mint#1]
```
STC@DESKTOP:~/split-mint$ yarn start
yarn run v1.22.17
$ node -r dotenv/config mintSplit.js
Starting balance for treasury: 7.9760176
file:///home/STC/split-mint/mintSplit.js:46
                console.log(`Starting balance for account ${i + 1}: ${startBalance.lamports / LAMPORTS_PER_SOL}`)
                                                                                   ^

TypeError: Cannot read properties of null (reading 'lamports')
    at handleTransaction (file:///home/STC/split-mint/mintSplit.js:46:84)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///home/STC/split-mint/mintSplit.js:75:9
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by solanatreehouseclub** [comment]
Due to not having sol in accounts to be split to. What is the technical limitation that a wallet must have funds for it to work?

**Comment by stephenwilliams1990** [comment]
If you run connection.getAccountInfo(<account>) and it returns null or undefined, this usually means that the account passed has not been initialized. If an initialized account has zero funds in it, it should not matter. Have you potentially passed in an uninitialized account?

**Comment by solanatreehouseclub** [comment]
Yes, thanks for the explanation.
